theme: jekyll-theme-dinky
title: GDI-DE Arbeitskreis Metadaten
description: GDI-DE Architektur der Geodateninfrastruktur Deutschland - Konventionen zu Metadaten
show_downloads: "true"
github:
  zip_url: https://www.gdi-de.org/SharedDocs/Downloads/DE/GDI-DE/Dokumente/Konventionen_zu_Metadaten_V2.0.3.pdf
  another_url: https://github.com/alitka/gdi-de-metadaten-konventionen/blob/master/_layouts/page.html

# Reading Files
include:
  - _pages

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: default
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: default
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: default
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: default
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: default
      author_profile: true
      share: true
