theme: jekyll-theme-dinky
remote_theme: pages-themes/dinky@v0.2.0
title: GDI-DE Arbeitskreis Metadaten
description: GDI-DE Architektur der Geodateninfrastruktur Deutschland - Konventionen zu Metadaten
show_downloads: "true"
github:
  zip_url: https://wiki.gdi-de.org/download/attachments/3344909/Architektur_GDI_DE_Konventionen_Metadaten_v2_0_3.pdf
  another_url: https://wiki.gdi-de.org/display/AKMD
  repository_url: https://github.com/alitka/gdi-de-metadaten-ats/tree/2.0.3

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
