theme: jekyll-theme-slate
logo: https://www.gdi-de.org/SiteGlobals/StyleBundles/Bilder/Farbschema/logo_gdi.png;jsessionid=4DF24205651F49E10D434E0062959BA3?__blob=normal&v=11
title: GDI-DE Architektur der Geodateninfrastruktur Deutschland - Konventionen zu Metadaten
description: Arbeitskreis Metadaten
